services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - network

  django-web:
    build: ./djang/
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
      - central
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    networks:
      - network

  nginx:
    build: ./nginx/
    image: nginx
    networks:
      - network
    ports:
      - '443:443'
    container_name: nginx
    restart: always
    depends_on:
         - django-web
  
  central:
    build: ./central/
    networks:
      - network
    container_name: central
    restart: always
    ports:
      - "7777:7777"

  chat:
    build: ./chat/
    networks:
      - network
    container_name: chat
    restart: always
    depends_on:
      - central
    ports:
      - "7878:7878"

volumes:
  postgres_data:

networks:
  network:
    driver: bridge