version: '3'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django-web:
    build: ./djang/
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
 
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      HOST_ADDRESS: ${HOST_ADDRESS}
    env_file:
      - .env

  nginx:
    build: ./nginx/
    image: nginx
    networks:
      - network
    ports:
      - '1443:443'
    container_name: nginx
<<<<<<< HEAD
=======
    ports:
      - '443:443'
      - '80:80'  # Expose port 80 for HTTP
>>>>>>> 534b6f482d8c418ce526fee416a441746fe077b8
    restart: always
    depends_on:
         - django-web

volumes:
  postgres_data:

networks:
  network: