# Generated by Django 4.2.11 on 2024-11-04 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('emailVerified', models.BooleanField(default=False)),
                ('emailVerificationToken', models.CharField(max_length=200, null=True)),
                ('emailVerificationTokenExpiration', models.DateTimeField(null=True)),
                ('forgotPasswordCode', models.CharField(max_length=100, null=True)),
                ('forgotPasswordCodeExpiration', models.DateTimeField(null=True)),
                ('has_2fa', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(max_length=200, null=True)),
                ('totp_config_url', models.CharField(max_length=200, null=True)),
                ('account_deleted', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
