# Generated by Django 4.2.11 on 2024-11-04 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('emailVerified', models.BooleanField(default=False)),
                ('emailVerificationToken', models.CharField(max_length=200, null=True)),
                ('emailVerificationTokenExpiration', models.DateTimeField(null=True)),
                ('forgotPasswordCode', models.CharField(max_length=100, null=True)),
                ('forgotPasswordCodeExpiration', models.DateTimeField(null=True)),
                ('has_2fa', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(max_length=200, null=True)),
                ('totp_config_url', models.CharField(max_length=200, null=True)),
                ('account_deleted', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('elo', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1_score', models.IntegerField(null=True)),
                ('player_2_score', models.IntegerField(null=True)),
                ('match_id', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_1', to='polls.account')),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_2', to='polls.account')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='polls.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
