# Generated by Django 5.1.4 on 2024-12-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_account_totp_config_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='totp_config_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='totp_secret',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
