# Generated by Django 5.1.4 on 2025-01-03 12:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_account_match_delete_player'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_deleted',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='elo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='emailVerificationToken',
        ),
        migrations.RemoveField(
            model_name='account',
            name='emailVerificationTokenExpiration',
        ),
        migrations.RemoveField(
            model_name='account',
            name='emailVerified',
        ),
        migrations.RemoveField(
            model_name='account',
            name='forgotPasswordCode',
        ),
        migrations.RemoveField(
            model_name='account',
            name='forgotPasswordCodeExpiration',
        ),
        migrations.RemoveField(
            model_name='account',
            name='has_2fa',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='account',
            name='totp_config_url',
        ),
        migrations.RemoveField(
            model_name='account',
            name='totp_secret',
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='account',
            name='blockedUsers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='emailAlerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='favoritesChannels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='follows',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='friendRequests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='is42',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='isOfficial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='nbNewNotifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='resetPasswordID',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default='online', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
