# Generated by Django 5.1.4 on 2025-01-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_account_blockmodel_friendmodel_friendrequestmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default='offline', max_length=150),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histo_id', models.IntegerField()),
                ('goal_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='polls.match')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='polls.account')),
            ],
        ),
    ]
