# Generated by Django 5.1.4 on 2024-12-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_account_totp_config_url_account_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='totp_config_url',
        ),
        migrations.RemoveField(
            model_name='account',
            name='totp_secret',
        ),
    ]
