# Generated by Django 5.1.4 on 2025-01-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_account_status_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='is42',
            field=models.BooleanField(default=False),
        ),
    ]
