# Generated by Django 5.1.4 on 2024-12-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_account_totp_config_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_deleted',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='elo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
