# Generated by Django 5.1.4 on 2024-12-17 13:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_account_account_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='blockedUsers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='emailAlerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='favoritesChannels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='follows',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='friendRequests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='is42',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='isOfficial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='nbNewNotifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='resetPasswordID',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default='online', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
